[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "20"
  PYTHON_VERSION = ""
  REACT_ROUTER_PRERENDER = "true"

# Function redirects first (higher priority)
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# API proxy for functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "build/client"