[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "20"
  PYTHON_VERSION = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "build/client"